// Key to send with requests for information
var LOGIN_KEY =  'login';

// Variable to keep the current page
var page = null;

// mapping between hostnames and functions to fetch form information
var pages = {
	'https://idp.kuleuven.be/idp/view/login.htm': getKuleuvenForm,
	'https://idp.groept.be/idp/view/login.htm': getGroepTForm,
	'https://netlogin.kuleuven.be/cgi-bin/wayf.pl' : getNetloginForm
}

// Register for message replies
safari.self.addEventListener("message", login, false);

// iterate over all possible pages
for(var p in pages){
	// If we are on page for which login is implemented
	if(document.location.href.indexOf(p) == 0) {
		// Store the page we're on, so we can use it later to extract the dom elements
		page = p;
		// Request credentials from global page
		safari.self.tab.dispatchMessage("getInfo",LOGIN_KEY);
	}
}

// This function is called when the credentials are available
function login(event){
		// We are only interested in events generated by requests this script made
		if(event.name !== LOGIN_KEY){
			return;
		}
		// Extract username and password
		var username = event.message.username;
		var password = event.message.password;
		// Fetch form and form input fields
		data = pages[page]();
		// Fill in the fields
		data.usernameField.value = username;
		data.passwordField.value = password;
		// Submit the form
		data.form.submit();
}

// Get form and input fields from the KULeuven shibboleth page
function getKuleuvenForm(){
	var response = new Object();
	// Get the form and fields by id.
	response.form = document.getElementById('loginForm');
	response.usernameField = document.getElementById('username');
	response.passwordField = document.getElementById('password');
	// hack: form.submit() only works when there's no element named 'submit'
	response.form.elements['submit'].name = 'btnSubmit';
	return response;
}

// Get form and input fields from the GroepT shibboleth page
function getGroepTForm(){
	var response = new Object();
	// Get the form and fields by id.
	response.form = document.getElementById('login');
	response.usernameField = document.getElementById('username');
	response.passwordField = document.getElementById('password');
	return response;
}

// Get form and input fields from the netlogin page
function getNetloginForm(){
	var response = new Object();
	response.form = document.forms['netlogin'];
	// hack: form.submit() only works when there's no element named 'submit'
	response.form.elements['submit'].name = 'btnSubmit';
	// extract username and password fields
	for(x in response.form.elements){
		var field = response.form.elements[x]; 
		if(field.type == 'text'){
			// username field
			response.usernameField = field;
		}
		if(field.type == 'password'){
			// password field
			response.passwordField = field;
		}
	}
	return response;
}

