// Variable to keep the current page
var page = null;

// mapping between hostnames and functions to fetch form information
var pages = {
	'idp.kuleuven.be': getShibbolethForm,
	'idp.groept.be': getShibbolethForm,
	'netlogin.kuleuven.be' : getNetloginForm
}

// Register for message replies
safari.self.addEventListener("message", login, false);

// iterate over all possible pages
for(var p in pages){
	// If we are on page for which login is implemented
	if(document.location.host == p) {
		// Store the page we're on, so we can use it later to extract the dom elements
		page = p;
		// Request credentials from global page
		safari.self.tab.dispatchMessage("getSetting",'credentials');
	}
}

// This function is called when the credentials are available
function login(event){
		// We are only interested in events generated by available credentials
		if(event.name !== 'credentials'){
			return;
		}
		// Extract username and password
		var username = event.message.username;
		var password = event.message.password;
		if(username == undefined || password == undefined){
			alert('Kotnet Login kan je automatisch inloggen op deze pagina.\nGelieve daarvoor wel eerst je login-gegevens in te vullen in de instellingen.')
			return;
		}
		// Fetch form and form input fields
		data = pages[page]();
		// Fill in the fields
		data.usernameField.value = username;
		data.passwordField.value = password;
		// Submit the form
		data.form.submit();
}

// Get form and input fields from the shibboleth page
function getShibbolethForm(){
	var response = new Object();
	// Get the form and fields by id.
	response.form = document.getElementById('loginForm');
	response.usernameField = document.getElementById('username');
	response.passwordField = document.getElementById('password');
	// hack: form.submit() only works when there's no element named 'submit'
	response.form.elements['submit'].name = 'btnSubmit';
	return response;
}

// Get form and input fields from the netlogin page
function getNetloginForm(){
	var response = new Object();
	var form = null;
	forms = document.forms['netlogin'];
	// hack: form.submit() only works when there's no element named 'submit'
	response.form.elements['submit'].name = 'btnSubmit';
	// extract username and password fields
	for(field in response.form.elements){
		if(field.type == 'text'){
			// username field
			response.usernameField = field;
		}
		if(field.type == 'password'){
			// password field
			response.passwordField = field;
		}
	}
	return response;
}

